**Pandas** - Basically pandas used for handling data (especially tables/csv files).

* Data Analysis (Sales, Records, Report)

* Prepare data before Machine Learning

* Advance version of excel with coding

In [1]:
import pandas as pd

In [4]:
emp = pd.read_csv('emp.csv')

In [5]:
emp.columns

Index(['empno', 'ename', 'job', 'mgr', 'hiredate', 'sal', 'comm', 'deptno'], dtype='object')

In [6]:
emp.shape # (Row, Column)

(14, 8)

In [7]:
print("Rows: ", emp.shape[0])
print("Columns: ", emp.shape[1])

Rows:  14
Columns:  8

In [8]:
len(emp) # SELECT COUNT(*) FROM emp

14

In [9]:
emp # SELECT * FROM emp

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10

In [10]:
emp.head() # SELECT * FROM emp LIMIT 5

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30

In [11]:
emp.head(len(emp))

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10

In [12]:
emp.head(3)

   empno  ename        job     mgr    hiredate   sal  comm  deptno
0   7839   KING  PRESIDENT     NaN  11/17/2001  5000   NaN      10
1   7698  BLAKE    MANAGER  7839.0  05/01/2001  2850   NaN      30
2   7782  CLARK    MANAGER  7839.0  06/09/2001  2450   NaN      10

In [13]:
emp.tail()

    empno   ename      job     mgr    hiredate   sal  comm  deptno
9    7902    FORD  ANALYST  7566.0  02/03/2001  3000   NaN      20
10   7369   SMITH    CLERK  7902.0  12/17/2000   800   NaN      20
11   7788   SCOTT  ANALYST  7566.0  04/19/2007  3000   NaN      20
12   7876   ADAMS    CLERK  7788.0  05/23/2007  1100   NaN      20
13   7934  MILLER    CLERK  7782.0  01/23/2002  1300   NaN      10

In [14]:
emp.sample(4)

    empno   ename        job     mgr    hiredate   sal  comm  deptno
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975   NaN      20
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000   NaN      10
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300   NaN      10
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000   NaN      20

In [15]:
emp[['empno', 'ename', 'sal']].head() # emp.head()[['empno', 'ename', 'sal']]

   empno   ename   sal
0   7839    KING  5000
1   7698   BLAKE  2850
2   7782   CLARK  2450
3   7566   JONES  2975
4   7654  MARTIN  1250

In [16]:
cols = ['empno', 'ename', 'sal']
emp[cols].head(14) # SELECT 'empno', 'ename', 'sal', 'dept

    empno   ename   sal
0    7839    KING  5000
1    7698   BLAKE  2850
2    7782   CLARK  2450
3    7566   JONES  2975
4    7654  MARTIN  1250
5    7499   ALLEN  1600
6    7844  TURNER  1500
7    7900   JAMES   950
8    7521    WARD  1250
9    7902    FORD  3000
10   7369   SMITH   800
11   7788   SCOTT  3000
12   7876   ADAMS  1100
13   7934  MILLER  1300

In [17]:
emp.sort_values(by='sal', ascending=False)

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20

In [18]:
emp[cols].sort_values(by="ename")

    empno   ename   sal
12   7876   ADAMS  1100
5    7499   ALLEN  1600
1    7698   BLAKE  2850
2    7782   CLARK  2450
9    7902    FORD  3000
7    7900   JAMES   950
3    7566   JONES  2975
0    7839    KING  5000
4    7654  MARTIN  1250
13   7934  MILLER  1300
11   7788   SCOTT  3000
10   7369   SMITH   800
6    7844  TURNER  1500
8    7521    WARD  1250

In [19]:
emp.rename(columns={"sal" : "Salary", "ename" : "Employee"})

# select empno , sal as salary, ename as Employee from emp

    empno Employee        job     mgr    hiredate  Salary    comm  deptno
0    7839     KING  PRESIDENT     NaN  11/17/2001    5000     NaN      10
1    7698    BLAKE    MANAGER  7839.0  05/01/2001    2850     NaN      30
2    7782    CLARK    MANAGER  7839.0  06/09/2001    2450     NaN      10
3    7566    JONES    MANAGER  7839.0  04/02/2001    2975     NaN      20
4    7654   MARTIN   SALESMAN  7698.0  09/28/2001    1250  1400.0      30
5    7499    ALLEN   SALESMAN  7698.0  02/20/2001    1600   300.0      30
6    7844   TURNER   SALESMAN  7698.0  09/08/2001    1500     0.0      30
7    7900    JAMES      CLERK  7698.0  12/03/2001     950     NaN      30
8    7521     WARD   SALESMAN  7698.0  02/22/2001    1250   500.0      30
9    7902     FORD    ANALYST  7566.0  02/03/2001    3000     NaN      20
10   7369    SMITH      CLERK  7902.0  12/17/2000     800     NaN      20
11   7788    SCOTT    ANALYST  7566.0  04/19/2007    3000     NaN      20
12   7876    ADAMS      CLERK  7788.0  05/23/2007    1100     NaN      20
13   7934   MILLER      CLERK  7782.0  01/23/2002    1300     NaN      10

In [22]:
emp2 = emp[cols].copy()
emp2['Annual Salary'] = emp2['sal'] * 12  # emp2.sal * 12
emp2

    empno   ename   sal  Annual Salary
0    7839    KING  5000          60000
1    7698   BLAKE  2850          34200
2    7782   CLARK  2450          29400
3    7566   JONES  2975          35700
4    7654  MARTIN  1250          15000
5    7499   ALLEN  1600          19200
6    7844  TURNER  1500          18000
7    7900   JAMES   950          11400
8    7521    WARD  1250          15000
9    7902    FORD  3000          36000
10   7369   SMITH   800           9600
11   7788   SCOTT  3000          36000
12   7876   ADAMS  1100          13200
13   7934  MILLER  1300          15600

In [24]:
cols2 = ['empno', 'ename', 'sal', 'deptno']

In [25]:
emp[cols2][(emp.deptno == 10) | (emp.sal > 2000)]
# SELECT empno, ename, sal, deptno FROM emp
# WHERE (emp.deptno = 10) OR (emp.sal > 2000)

    empno   ename   sal  deptno
0    7839    KING  5000      10
1    7698   BLAKE  2850      30
2    7782   CLARK  2450      10
3    7566   JONES  2975      20
9    7902    FORD  3000      20
11   7788   SCOTT  3000      20
13   7934  MILLER  1300      10

In [26]:
emp[cols][(emp.sal >=1000) & (emp.sal <=3000)]
# SELECT empno, ename, sal FROM emp
# WHERE (emp.sal >= 1000) AND (emp.sal <= 3000)

    empno   ename   sal
1    7698   BLAKE  2850
2    7782   CLARK  2450
3    7566   JONES  2975
4    7654  MARTIN  1250
5    7499   ALLEN  1600
6    7844  TURNER  1500
8    7521    WARD  1250
9    7902    FORD  3000
11   7788   SCOTT  3000
12   7876   ADAMS  1100
13   7934  MILLER  1300

In [27]:
emp[emp.ename.str.endswith('N')] # %N

   empno   ename       job     mgr    hiredate   sal    comm  deptno
4   7654  MARTIN  SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5   7499   ALLEN  SALESMAN  7698.0  02/20/2001  1600   300.0      30

In [28]:
emp[emp.ename.str.startswith('A')] # A%

    empno  ename       job     mgr    hiredate   sal   comm  deptno
5    7499  ALLEN  SALESMAN  7698.0  02/20/2001  1600  300.0      30
12   7876  ADAMS     CLERK  7788.0  05/23/2007  1100    NaN      20

In [29]:
emp[(emp.ename.str.startswith('A')) & (emp.ename.str.endswith('N'))]

   empno  ename       job     mgr    hiredate   sal   comm  deptno
5   7499  ALLEN  SALESMAN  7698.0  02/20/2001  1600  300.0      30

In [30]:
emp[cols2][emp.ename.str.endswith('N')] # %N

   empno   ename   sal  deptno
4   7654  MARTIN  1250      30
5   7499   ALLEN  1600      30

In [31]:
emp[cols2][emp.ename.str.contains('A')] # %A%

    empno   ename   sal  deptno
1    7698   BLAKE  2850      30
2    7782   CLARK  2450      10
4    7654  MARTIN  1250      30
5    7499   ALLEN  1600      30
7    7900   JAMES   950      30
8    7521    WARD  1250      30
12   7876   ADAMS  1100      20

In [32]:
emp[emp.ename.str.startswith('A')]

    empno  ename       job     mgr    hiredate   sal   comm  deptno
5    7499  ALLEN  SALESMAN  7698.0  02/20/2001  1600  300.0      30
12   7876  ADAMS     CLERK  7788.0  05/23/2007  1100    NaN      20

In [33]:
emp2[emp2.ename.str.startswith('A') & emp2['ename'].str.endswith('N')]
# SELECT empno, ename, sal FROM emp
# WHERE emp.ename LIKE 'A%' AND emp.ename LIKE '%N' # --- LIKE 'A%N'

   empno  ename   sal  Annual Salary
5   7499  ALLEN  1600          19200

In [36]:
emp.agg(TotalEmp=('empno', 'count'), AvgSal=('sal', 'mean'), SumSal=('sal', 'sum'))
# SELECT COUNT(empno) AS TotalEmp, AVG(sal) AS AvgSal, SUM(sal) AS SumSal FROM emp

          empno           sal
TotalEmp   14.0           NaN
AvgSal      NaN   2073.214286
SumSal      NaN  29025.000000

*Transpose*

In [37]:
emp.agg(TotalEmp=('empno', 'count'), AvgSal=('sal', 'mean'), SumSal=('sal', 'sum')).T

       TotalEmp       AvgSal   SumSal
empno      14.0          NaN      NaN
sal         NaN  2073.214286  29025.0

In [38]:
emp02 =  emp.groupby('deptno').agg(TotalEmp = ('empno', 'count'), \
                                      AvgSal = ('sal', 'mean'), SumSal = ('sal', 'sum'))
emp02

        TotalEmp       AvgSal  SumSal
deptno
10             3  2916.666667    8750
20             5  2175.000000   10875
30             6  1566.666667    9400

In [39]:
emp02[emp02.TotalEmp > 3]
# SELECT deptno, COUNT(empno) AS TotalEmp, AVG(sal) AS AvgSal, SUM(sal) AS SumSal
# FROM emp
# GROUP BY deptno
# HAVING TotalEmp > 3

        TotalEmp       AvgSal  SumSal
deptno
20             5  2175.000000   10875
30             6  1566.666667    9400

In [40]:
emp.groupby(['deptno', 'job']).agg(TotalEmp = ('empno', 'count'), \
AvgSal = ('sal', 'mean'), SumSal = ('sal', 'sum'))
# SELECT deptno, job, COUNT(empno) AS TotalEmp, AVG(sal) AS AvgSal, SUM(sal) AS Sum
# FROM emp
# GROUP BY deptno, job

                  TotalEmp  AvgSal  SumSal
deptno job
10     CLERK             1  1300.0    1300
       MANAGER           1  2450.0    2450
       PRESIDENT         1  5000.0    5000
20     ANALYST           2  3000.0    6000
       CLERK             2   950.0    1900
       MANAGER           1  2975.0    2975
30     CLERK             1   950.0     950
       MANAGER           1  2850.0    2850
       SALESMAN          4  1400.0    5600

In [41]:
emp.groupby(['deptno', 'job']).agg(TotalEmp = ('empno', 'count'), \
AvgSal = ('sal', 'mean'), SumSal = ('sal', 'sum'))

                  TotalEmp  AvgSal  SumSal
deptno job
10     CLERK             1  1300.0    1300
       MANAGER           1  2450.0    2450
       PRESIDENT         1  5000.0    5000
20     ANALYST           2  3000.0    6000
       CLERK             2   950.0    1900
       MANAGER           1  2975.0    2975
30     CLERK             1   950.0     950
       MANAGER           1  2850.0    2850
       SALESMAN          4  1400.0    5600

*Join (merge)*

In [43]:
e = emp.copy() # pd.read_csv(r"D://DataSets//emp.csv")
d = pd.read_csv("dept.csv")
print(e.columns)
print(d.columns)

Index(['empno', 'ename', 'job', 'mgr', 'hiredate', 'sal', 'comm', 'deptno'], dtype='object')
Index(['deptno', 'dname', 'loc'], dtype='object')

In [44]:
e.head()

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30

In [45]:
d

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [46]:
# JOIN all same column(s) name

In [47]:
pd.merge(e, d)

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,ACCOUNTING,NEW YORK
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,SALES,CHICAGO
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,ACCOUNTING,NEW YORK
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,SALES,CHICAGO
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,30,SALES,CHICAGO
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,30,SALES,CHICAGO
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,30,SALES,CHICAGO
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,30,SALES,CHICAGO
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,20,RESEARCH,DALLAS
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,20,RESEARCH,DALLAS
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,20,RESEARCH,DALLAS
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,20,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,10,ACCOUNTING,NEW YORK

In [48]:
# JOIN specific same column(s) name
# Joining Type

*inner join*

Same column Name in both dataframes

In [49]:
pd.merge(e, d, on='deptno', how='inner')

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,ACCOUNTING,NEW YORK
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,SALES,CHICAGO
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,ACCOUNTING,NEW YORK
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,SALES,CHICAGO
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,30,SALES,CHICAGO
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,30,SALES,CHICAGO
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,30,SALES,CHICAGO
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,30,SALES,CHICAGO
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,20,RESEARCH,DALLAS
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,20,RESEARCH,DALLAS
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,20,RESEARCH,DALLAS
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,20,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,10,ACCOUNTING,NEW YORK

Different Column Names in both dataframes

In [50]:
pd.merge(e, d, left_on='deptno', right_on='deptno', how='inner')

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,ACCOUNTING,NEW YORK
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,SALES,CHICAGO
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,ACCOUNTING,NEW YORK
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,SALES,CHICAGO
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,30,SALES,CHICAGO
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,30,SALES,CHICAGO
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,30,SALES,CHICAGO
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,30,SALES,CHICAGO
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,20,RESEARCH,DALLAS
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,20,RESEARCH,DALLAS
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,20,RESEARCH,DALLAS
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,20,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,10,ACCOUNTING,NEW YORK

*Outer Join*

In [51]:
pd.merge(e, d, how='right') # 'left'; 'outer'

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7839.0,KING,PRESIDENT,NaN,11/17/2001,5000.0,NaN,10,ACCOUNTING,NEW YORK
1,7782.0,CLARK,MANAGER,7839.0,06/09/2001,2450.0,NaN,10,ACCOUNTING,NEW YORK
2,7934.0,MILLER,CLERK,7782.0,01/23/2002,1300.0,NaN,10,ACCOUNTING,NEW YORK
3,7566.0,JONES,MANAGER,7839.0,04/02/2001,2975.0,NaN,20,RESEARCH,DALLAS
4,7902.0,FORD,ANALYST,7566.0,02/03/2001,3000.0,NaN,20,RESEARCH,DALLAS
5,7369.0,SMITH,CLERK,7902.0,12/17/2000,800.0,NaN,20,RESEARCH,DALLAS
6,7788.0,SCOTT,ANALYST,7566.0,04/19/2007,3000.0,NaN,20,RESEARCH,DALLAS
7,7876.0,ADAMS,CLERK,7788.0,05/23/2007,1100.0,NaN,20,RESEARCH,DALLAS
8,7698.0,BLAKE,MANAGER,7839.0,05/01/2001,2850.0,NaN,30,SALES,CHICAGO
9,7654.0,MARTIN,SALESMAN,7698.0,09/28/2001,1250.0,1400.0,30,SALES,CHICAGO
10,7499.0,ALLEN,SALESMAN,7698.0,02/20/2001,1600.0,300.0,30,SALES,CHICAGO
11,7844.0,TURNER,SALESMAN,7698.0,09/08/2001,1500.0,0.0,30,SALES,CHICAGO
12,7900.0,JAMES,CLERK,7698.0,12/03/2001,950.0,NaN,30,SALES,CHICAGO
13,7521.0,WARD,SALESMAN,7698.0,02/22/2001,1250.0,500.0,30,SALES,CHICAGO
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,OPERATIONS,BOSTON

In [52]:
pd.merge(e, d, on='deptno', how='outer', indicator = True)

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,_merge
0,7839.0,KING,PRESIDENT,NaN,11/17/2001,5000.0,NaN,10,ACCOUNTING,NEW YORK,both
1,7782.0,CLARK,MANAGER,7839.0,06/09/2001,2450.0,NaN,10,ACCOUNTING,NEW YORK,both
2,7934.0,MILLER,CLERK,7782.0,01/23/2002,1300.0,NaN,10,ACCOUNTING,NEW YORK,both
3,7566.0,JONES,MANAGER,7839.0,04/02/2001,2975.0,NaN,20,RESEARCH,DALLAS,both
4,7902.0,FORD,ANALYST,7566.0,02/03/2001,3000.0,NaN,20,RESEARCH,DALLAS,both
5,7369.0,SMITH,CLERK,7902.0,12/17/2000,800.0,NaN,20,RESEARCH,DALLAS,both
6,7788.0,SCOTT,ANALYST,7566.0,04/19/2007,3000.0,NaN,20,RESEARCH,DALLAS,both
7,7876.0,ADAMS,CLERK,7788.0,05/23/2007,1100.0,NaN,20,RESEARCH,DALLAS,both
8,7698.0,BLAKE,MANAGER,7839.0,05/01/2001,2850.0,NaN,30,SALES,CHICAGO,both
9,7654.0,MARTIN,SALESMAN,7698.0,09/28/2001,1250.0,1400.0,30,SALES,CHICAGO,both
10,7499.0,ALLEN,SALESMAN,7698.0,02/20/2001,1600.0,300.0,30,SALES,CHICAGO,both
11,7844.0,TURNER,SALESMAN,7698.0,09/08/2001,1500.0,0.0,30,SALES,CHICAGO,both
12,7900.0,JAMES,CLERK,7698.0,12/03/2001,950.0,NaN,30,SALES,CHICAGO,both
13,7521.0,WARD,SALESMAN,7698.0,02/22/2001,1250.0,500.0,30,SALES,CHICAGO,both
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,OPERATIONS,BOSTON,right_only

In [53]:
pd.merge(e, d, on='deptno', how='inner', validate = 'many_to_one') # 'on_to_many'

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,ACCOUNTING,NEW YORK
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,SALES,CHICAGO
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,ACCOUNTING,NEW YORK
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,SALES,CHICAGO
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,30,SALES,CHICAGO
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,30,SALES,CHICAGO
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,30,SALES,CHICAGO
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,30,SALES,CHICAGO
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,20,RESEARCH,DALLAS
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,20,RESEARCH,DALLAS
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,20,RESEARCH,DALLAS
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,20,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,10,ACCOUNTING,NEW YORK

*Self Join: Two columns of One dataframe*

In [54]:
e = emp
m = emp

In [55]:
pd.merge(e, m, left_on='mgr', right_on='empno', how='inner')[['empno_x', 'ename_x', 'empno_y', 'ename_y']]
# SELECT e.empno, e.ename, e.mgr, m.ename
# FROM emp e INNER JOIN emp m ON e.mgr= m.empno

    empno_x ename_x  empno_y ename_y
0      7698   BLAKE     7839    KING
1      7782   CLARK     7839    KING
2      7566   JONES     7839    KING
3      7654  MARTIN     7698   BLAKE
4      7499   ALLEN     7698   BLAKE
5      7844  TURNER     7698   BLAKE
6      7900   JAMES     7698   BLAKE
7      7521    WARD     7698   BLAKE
8      7902    FORD     7566   JONES
9      7369   SMITH     7902    FORD
10     7788   SCOTT     7566   JONES
11     7876   ADAMS     7788   SCOTT
12     7934  MILLER     7782   CLARK

In [56]:
pd.merge(e, m, left_on='mgr', right_on='empno', how='outer')[['empno_x', 'ename_x', 'empno_y', 'ename_y']]

    empno_x ename_x  empno_y ename_y
0       NaN     NaN   7369.0   SMITH
1       NaN     NaN   7499.0   ALLEN
2       NaN     NaN   7521.0    WARD
3    7902.0    FORD   7566.0   JONES
4    7788.0   SCOTT   7566.0   JONES
5       NaN     NaN   7654.0  MARTIN
6    7654.0  MARTIN   7698.0   BLAKE
7    7499.0   ALLEN   7698.0   BLAKE
8    7844.0  TURNER   7698.0   BLAKE
9    7900.0   JAMES   7698.0   BLAKE
10   7521.0    WARD   7698.0   BLAKE
11   7934.0  MILLER   7782.0   CLARK
12   7876.0   ADAMS   7788.0   SCOTT
13   7698.0   BLAKE   7839.0    KING
14   7782.0   CLARK   7839.0    KING
15   7566.0   JONES   7839.0    KING
16      NaN     NaN   7844.0  TURNER
17      NaN     NaN   7876.0   ADAMS
18      NaN     NaN   7900.0   JAMES
19   7369.0   SMITH   7902.0    FORD
20      NaN     NaN   7934.0  MILLER
21   7839.0    KING      NaN     NaN

In [57]:
pd.merge(e, m, left_on='mgr', right_on='empno', how='left')[['empno_x', 'ename_x', 'empno_y', 'ename_y']]

    empno_x ename_x  empno_y ename_y
0      7839    KING      NaN     NaN
1      7698   BLAKE   7839.0    KING
2      7782   CLARK   7839.0    KING
3      7566   JONES   7839.0    KING
4      7654  MARTIN   7698.0   BLAKE
5      7499   ALLEN   7698.0   BLAKE
6      7844  TURNER   7698.0   BLAKE
7      7900   JAMES   7698.0   BLAKE
8      7521    WARD   7698.0   BLAKE
9      7902    FORD   7566.0   JONES
10     7369   SMITH   7902.0    FORD
11     7788   SCOTT   7566.0   JONES
12     7876   ADAMS   7788.0   SCOTT
13     7934  MILLER   7782.0   CLARK

In [58]:
pd.merge(e, m, left_on='mgr', right_on='empno', how='right')[['empno_x', 'ename_x', 'empno_y', 'ename_y']]

    empno_x ename_x  empno_y ename_y
0    7698.0   BLAKE     7839    KING
1    7782.0   CLARK     7839    KING
2    7566.0   JONES     7839    KING
3    7654.0  MARTIN     7698   BLAKE
4    7499.0   ALLEN     7698   BLAKE
5    7844.0  TURNER     7698   BLAKE
6    7900.0   JAMES     7698   BLAKE
7    7521.0    WARD     7698   BLAKE
8    7934.0  MILLER     7782   CLARK
9    7902.0    FORD     7566   JONES
10   7788.0   SCOTT     7566   JONES
11      NaN     NaN     7654  MARTIN
12      NaN     NaN     7499   ALLEN
13      NaN     NaN     7844  TURNER
14      NaN     NaN     7900   JAMES
15      NaN     NaN     7521    WARD
16   7369.0   SMITH     7902    FORD
17      NaN     NaN     7369   SMITH
18   7876.0   ADAMS     7788   SCOTT
19      NaN     NaN     7876   ADAMS
20      NaN     NaN     7934  MILLER

*Set Operations*

In [59]:
j20 = emp.job[(emp.deptno==20)].unique()
print(j20)
j30 = emp.job[(emp.deptno==30)].unique()
print(j30)

['MANAGER' 'ANALYST' 'CLERK']
['MANAGER' 'SALESMAN' 'CLERK']

In [60]:
j20 = set(j20)
j20

{'ANALYST', 'CLERK', 'MANAGER'}

In [61]:
j30 = set(j30)
j30

{'CLERK', 'MANAGER', 'SALESMAN'}

*union*

In [62]:
union_set = j20.union(j30)
union_set

{'ANALYST', 'CLERK', 'MANAGER', 'SALESMAN'}

In [63]:
union_df = pd.DataFrame(list(union_set), columns=['job'])
union_df

        job
0  SALESMAN
1   ANALYST
2     CLERK
3   MANAGER

*intersection*

In [64]:
intersect_set = j20.intersection(j30)
intersect_set

{'CLERK', 'MANAGER'}

*minus*

In [65]:
minus_set2030 = j20.difference(j30)
minus_set2030

{'ANALYST'}

In [66]:
minus_set3020 = j30.difference(j20)
minus_set3020

{'SALESMAN'}

*symmetric difference*

In [67]:
symdiff_set = j20.symmetric_difference(j30)
symdiff_set

{'ANALYST', 'SALESMAN'}