In [ ]:
import pandas as pd

In [ ]:
emp = pd.read_csv(r"D://DataSets//emp.csv")
# for colab       r"/content/emp.csv"

In [ ]:
emp.columns

Index(['empno', 'ename', 'job', 'mgr', 'hiredate', 'sal', 'comm', 'deptno'], dtype='object')

In [ ]:
emp.shape    # (Row, Column)

(14, 8)

In [ ]:
print("Rows: ", emp.shape[0])
print("Columns: ", emp.shape[1])

Rows:  14
Columns:  8

In [ ]:
len(emp)     # SELECT COUNT(*) FROM emp

14

In [ ]:
emp          # SELECT * FROM emp

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10

In [ ]:
emp.head()           # SELECT * FROM emp LIMIT 5

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30

In [ ]:
emp.head(len(emp))

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10

In [ ]:
emp.head(3)

   empno  ename        job     mgr    hiredate   sal  comm  deptno
0   7839   KING  PRESIDENT     NaN  11/17/2001  5000   NaN      10
1   7698  BLAKE    MANAGER  7839.0  05/01/2001  2850   NaN      30
2   7782  CLARK    MANAGER  7839.0  06/09/2001  2450   NaN      10

In [ ]:
emp.tail()

    empno   ename      job     mgr    hiredate   sal  comm  deptno
9    7902    FORD  ANALYST  7566.0  02/03/2001  3000   NaN      20
10   7369   SMITH    CLERK  7902.0  12/17/2000   800   NaN      20
11   7788   SCOTT  ANALYST  7566.0  04/19/2007  3000   NaN      20
12   7876   ADAMS    CLERK  7788.0  05/23/2007  1100   NaN      20
13   7934  MILLER    CLERK  7782.0  01/23/2002  1300   NaN      10

In [ ]:
emp.sample(4)

    empno  ename      job     mgr    hiredate   sal  comm  deptno
2    7782  CLARK  MANAGER  7839.0  06/09/2001  2450   NaN      10
12   7876  ADAMS    CLERK  7788.0  05/23/2007  1100   NaN      20
1    7698  BLAKE  MANAGER  7839.0  05/01/2001  2850   NaN      30
7    7900  JAMES    CLERK  7698.0  12/03/2001   950   NaN      30

In [ ]:
emp[['empno', 'ename', 'sal']].head()   #  emp.head()[['empno', 'ename', 'sal']]

   empno   ename   sal
0   7839    KING  5000
1   7698   BLAKE  2850
2   7782   CLARK  2450
3   7566   JONES  2975
4   7654  MARTIN  1250

In [ ]:
cols = ['empno', 'ename', 'sal']
emp[cols].head(14)                          # SELECT 'empno', 'ename', 'sal', 'deptno' FROM emp

    empno   ename   sal
0    7839    KING  5000
1    7698   BLAKE  2850
2    7782   CLARK  2450
3    7566   JONES  2975
4    7654  MARTIN  1250
5    7499   ALLEN  1600
6    7844  TURNER  1500
7    7900   JAMES   950
8    7521    WARD  1250
9    7902    FORD  3000
10   7369   SMITH   800
11   7788   SCOTT  3000
12   7876   ADAMS  1100
13   7934  MILLER  1300

In [ ]:
emp.sort_values(by="sal", ascending=False)

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20

In [ ]:
emp[cols].sort_values(by="ename")
# SELECT empno, ename, sal FROM emp ORDER BY ename

    empno   ename   sal
12   7876   ADAMS  1100
5    7499   ALLEN  1600
1    7698   BLAKE  2850
2    7782   CLARK  2450
9    7902    FORD  3000
7    7900   JAMES   950
3    7566   JONES  2975
0    7839    KING  5000
4    7654  MARTIN  1250
13   7934  MILLER  1300
11   7788   SCOTT  3000
10   7369   SMITH   800
6    7844  TURNER  1500
8    7521    WARD  1250

In [ ]:
emp.rename(columns = {'sal':'Salary', 'ename': 'Employee' })

# SELECT empno, sal AS 'Salary', ename AS 'Employee' FROM emp

    empno Employee        job     mgr    hiredate  Salary    comm  deptno
0    7839     KING  PRESIDENT     NaN  11/17/2001    5000     NaN      10
1    7698    BLAKE    MANAGER  7839.0  05/01/2001    2850     NaN      30
2    7782    CLARK    MANAGER  7839.0  06/09/2001    2450     NaN      10
3    7566    JONES    MANAGER  7839.0  04/02/2001    2975     NaN      20
4    7654   MARTIN   SALESMAN  7698.0  09/28/2001    1250  1400.0      30
5    7499    ALLEN   SALESMAN  7698.0  02/20/2001    1600   300.0      30
6    7844   TURNER   SALESMAN  7698.0  09/08/2001    1500     0.0      30
7    7900    JAMES      CLERK  7698.0  12/03/2001     950     NaN      30
8    7521     WARD   SALESMAN  7698.0  02/22/2001    1250   500.0      30
9    7902     FORD    ANALYST  7566.0  02/03/2001    3000     NaN      20
10   7369    SMITH      CLERK  7902.0  12/17/2000     800     NaN      20
11   7788    SCOTT    ANALYST  7566.0  04/19/2007    3000     NaN      20
12   7876    ADAMS      CLERK  7788.0  05/23/2007    1100     NaN      20
13   7934   MILLER      CLERK  7782.0  01/23/2002    1300     NaN      10

In [ ]:
emp2 = emp[cols].copy()
emp2['Annual Salary'] = emp2['sal'] * 12     # emp2.sal * 12
emp2

### emp2.to_csv("D:\DataSets\emp2.csv", index = False)
# SELECT empno, ename, sal, sal*12 AS "Annual Salary" FROM emp2

    empno   ename   sal  Annual Salary
0    7839    KING  5000          60000
1    7698   BLAKE  2850          34200
2    7782   CLARK  2450          29400
3    7566   JONES  2975          35700
4    7654  MARTIN  1250          15000
5    7499   ALLEN  1600          19200
6    7844  TURNER  1500          18000
7    7900   JAMES   950          11400
8    7521    WARD  1250          15000
9    7902    FORD  3000          36000
10   7369   SMITH   800           9600
11   7788   SCOTT  3000          36000
12   7876   ADAMS  1100          13200
13   7934  MILLER  1300          15600

In [ ]:
cols2 = ['empno', 'ename', 'sal', 'deptno']

In [ ]:
emp[cols2][(emp.deptno == 10) | (emp.sal > 2000)]

# SELECT empno, ename, sal, deptno FROM emp
# WHERE (emp.deptno = 10) OR (emp.sal > 2000)

    empno   ename   sal  deptno
0    7839    KING  5000      10
1    7698   BLAKE  2850      30
2    7782   CLARK  2450      10
3    7566   JONES  2975      20
9    7902    FORD  3000      20
11   7788   SCOTT  3000      20
13   7934  MILLER  1300      10

In [ ]:
emp[cols][(emp.sal >=1000) & (emp.sal <=3000)]

# SELECT empno, ename, sal FROM emp
# WHERE (emp.sal >= 1000) AND (emp.sal <= 3000)

    empno   ename   sal
1    7698   BLAKE  2850
2    7782   CLARK  2450
3    7566   JONES  2975
4    7654  MARTIN  1250
5    7499   ALLEN  1600
6    7844  TURNER  1500
8    7521    WARD  1250
9    7902    FORD  3000
11   7788   SCOTT  3000
12   7876   ADAMS  1100
13   7934  MILLER  1300

In [ ]:
emp[emp.ename.str.endswith('N')]     # %N

   empno   ename       job     mgr    hiredate   sal    comm  deptno
4   7654  MARTIN  SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5   7499   ALLEN  SALESMAN  7698.0  02/20/2001  1600   300.0      30

In [ ]:
emp[emp.ename.str.startswith('A')]   # A%

    empno  ename       job     mgr    hiredate   sal   comm  deptno
5    7499  ALLEN  SALESMAN  7698.0  02/20/2001  1600  300.0      30
12   7876  ADAMS     CLERK  7788.0  05/23/2007  1100    NaN      20

In [ ]:
emp[(emp.ename.str.startswith('A')) & (emp.ename.str.endswith('N'))]

   empno  ename       job     mgr    hiredate   sal   comm  deptno
5   7499  ALLEN  SALESMAN  7698.0  02/20/2001  1600  300.0      30

In [ ]:
emp2 = emp[cols].copy()
emp2['Annual Salary'] = emp2['sal'] * 12     # emp2.sal * 12
emp2

### emp2.to_csv("D:\DataSets\emp2.csv", index = False)
# SELECT empno, ename, sal, sal*12 AS "Annual Salary" FROM emp2

    empno   ename   sal  Annual Salary
0    7839    KING  5000          60000
1    7698   BLAKE  2850          34200
2    7782   CLARK  2450          29400
3    7566   JONES  2975          35700
4    7654  MARTIN  1250          15000
5    7499   ALLEN  1600          19200
6    7844  TURNER  1500          18000
7    7900   JAMES   950          11400
8    7521    WARD  1250          15000
9    7902    FORD  3000          36000
10   7369   SMITH   800           9600
11   7788   SCOTT  3000          36000
12   7876   ADAMS  1100          13200
13   7934  MILLER  1300          15600

In [ ]:
cols2 = ['empno', 'ename', 'sal', 'deptno']

In [ ]:
emp[cols2][emp.ename.str.endswith('N')]    # %N

   empno   ename   sal  deptno
4   7654  MARTIN  1250      30
5   7499   ALLEN  1600      30

In [ ]:
emp[cols2][emp.ename.str.contains('A')]    # %A%

    empno   ename   sal  deptno
1    7698   BLAKE  2850      30
2    7782   CLARK  2450      10
4    7654  MARTIN  1250      30
5    7499   ALLEN  1600      30
7    7900   JAMES   950      30
8    7521    WARD  1250      30
12   7876   ADAMS  1100      20

In [ ]:
emp[emp.ename.str.startswith('A')]

    empno  ename       job     mgr    hiredate   sal   comm  deptno
5    7499  ALLEN  SALESMAN  7698.0  02/20/2001  1600  300.0      30
12   7876  ADAMS     CLERK  7788.0  05/23/2007  1100    NaN      20

In [ ]:
emp2[emp2.ename.str.startswith('A') & emp2['ename'].str.endswith('N')]

# SELECT empno, ename, sal FROM emp
# WHERE emp.ename LIKE 'A%' AND emp.ename LIKE '%N'   # --- LIKE 'A%N'

   empno  ename   sal  Annual Salary
5   7499  ALLEN  1600          19200

In [ ]:
emp.agg(TotalEmp = ('empno', 'count'), AvgSal = ('sal', 'mean'), SumSal = ('sal', 'sum'))

# SELECT COUNT(empno) AS TotalEmp, AVG(sal) AS AvgSal, SUM(sal) AS SumSal FROM emp

          empno           sal
TotalEmp   14.0           NaN
AvgSal      NaN   2073.214286
SumSal      NaN  29025.000000

### Transpose

In [ ]:
emp.agg(TotalEmp = ('empno', 'count'), AvgSal = ('sal', 'mean'), SumSal = ('sal', 'sum')).T

       TotalEmp       AvgSal   SumSal
empno      14.0          NaN      NaN
sal         NaN  2073.214286  29025.0

In [ ]:
emp02 = emp.groupby('deptno').agg(TotalEmp = ('empno', 'count'), \
                                  AvgSal = ('sal', 'mean'), SumSal = ('sal', 'sum')).reset_index()
emp02

# SELECT deptno, COUNT(empno) AS TotalEmp, AVG(sal) AS AvgSal, SUM(sal) AS SumSal
# FROM emp
# GROUP BY deptno

   deptno  TotalEmp       AvgSal  SumSal
0      10         3  2916.666667    8750
1      20         5  2175.000000   10875
2      30         6  1566.666667    9400